=== Pix4D/opf-spec/schema/calibrated_cameras.schema.json
{
    "$id": "calibrated_cameras.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "version": "1.0",
    "title": " Calibrated cameras",
    "description": "Definition of Calibrated Camera Parameters",
    "type": "object",
    "allOf": [
        {
            "$ref": "property.schema.json"
        }
    ],
    "properties": {
        "format": {
            "const": "application/opf-calibrated-cameras+json",
            "type": "string",
            "description": "For calibrated cameras it must be `\"application/opf-calibrated-cameras+json\"`"
        },
        "version": {
            "$ref": "version.schema.json"
        },
        "sensors": {
            "type": "array",
            "items": {
                "$ref": "calibrated_cameras.schema.json#/$defs/sensor"
            },
            "description": "Calibrated sensor parameters."
        },
        "cameras": {
            "type": "array",
            "items": {
                "$ref": "calibrated_cameras.schema.json#/$defs/camera"
            },
            "description": "Calibrated camera parameters."
        },
        "extensions": {}
    },
    "required": [
        "format",
        "version",
        "sensors",
        "cameras"
    ],
    "$defs": {
        "sensor": {
            "type": "object",
            "title": "Calibrated sensor",
            "allOf": [
                {
                    "$ref": "property.schema.json"
                }
            ],
            "properties": {
                "id": {
                    "allOf": [
                        {
                            "$ref": "uid64.schema.json"
                        }
                    ],
                    "description": "Unique ID of the sensor, it must appear in the input cameras."
                },
                "internals": {
                    "allOf": [
                        {
                            "$ref": "sensor_internals.schema.json"
                        }
                    ],
                    "description": "Calibrated sensor internal parameters."
                },
                "rig_relatives": {
                    "$ref": "calibrated_rig_relatives.schema.json"
                },
                "extensions": {}
            },
            "required": [
                "id",
                "internals"
            ]
        },
        "camera": {
            "type": "object",
            "title": "Calibrated camera",
            "allOf": [
                {
                    "$ref": "property.schema.json"
                }
            ],
            "properties": {
                "id": {
                    "allOf": [
                        {
                            "$ref": "uid64.schema.json"
                        }
                    ],
                    "description": "Unique ID of the camera, it must appear in the input cameras."
                },
                "sensor_id": {
                    "allOf": [
                        {
                            "$ref": "uid64.schema.json"
                        }
                    ],
                    "description": "Unique ID of the sensor used by this camera."
                },
                "position": {
                    "allOf": [
                        {
                            "$ref": "vector3d.schema.json"
                        }
                    ],
                    "description": "Calibrated coordinates in the processing CRS."
                },
                "orientation_deg": {
                    "allOf": [
                        {
                            "$ref": "vector3d.schema.json"
                        }
                    ],
                    "description": "Calibrated Omega-Phi-Kappa angles in degree representing a rotation R_x(\u03c9)R_y(\u03d5)R_z(\u03ba) from the image CS to the processing CRS."
                },
                "rolling_shutter": {
                    "allOf": [
                        {
                            "$ref": "vector3d.schema.json"
                        }
                    ],
                    "description": "Refer to [this document](https://s3.amazonaws.com/mics.pix4d.com/KB/documents/isprs_rolling_shutter_paper_final_2016.pdf)."
                },
                "extensions": {}
            },
            "required": [
                "id",
                "sensor_id",
                "position",
                "orientation_deg"
            ]
        }
    }
}

=== Pix4D/opf-spec/examples/calibrated-cameras.json
{
    "format": "application/opf-calibrated-cameras+json",
    "version": "1.0",
    "cameras": [
        {
            "id": 47292894,
            "orientation_deg": [
                3.3432,
                -5.2849554,
                9.345113
            ],
            "position": [
                483.054,
                13.957,
                28.12
            ],
            "sensor_id": 18493134
        },
        {
            "id": 57282923,
            "orientation_deg": [
                2.35224,
                -4.4422,
                9.03452
            ],
            "position": [
                483.04,
                13.972,
                28.12
            ],
            "sensor_id": 21845677
        },
        {
            "id": 28493939,
            "orientation_deg": [
                1.4753,
                10.5839,
                -2.94832
            ],
            "position": [
                243.054,
                521.957,
                31.12
            ],
            "sensor_id": 57282113
        }
    ],
    "sensors": [
        {
            "id": 18493134,
            "internals": {
                "affine": [
                    1676.296432,
                    0.0,
                    0.0,
                    1676.296432
                ],
                "is_p0_zero": true,
                "is_symmetric_affine": true,
                "polynomial": [
                    0.0,
                    1.0,
                    0.0152646,
                    -0.161096
                ],
                "principal_point_px": [
                    634.45,
                    481.23
                ],
                "type": "fisheye"
            }
        },
        {
            "id": 21845677,
            "internals": {
                "affine": [
                    1637.34211,
                    0.0,
                    0.0,
                    1637.34211
                ],
                "is_p0_zero": true,
                "is_symmetric_affine": true,
                "polynomial": [
                    0.0,
                    1.0,
                    0.0152646,
                    -0.161096
                ],
                "principal_point_px": [
                    641.12,
                    479.65
                ],
                "type": "fisheye"
            },
            "rig_relatives": {
                "rotation_angles_deg": [
                    -0.456,
                    1.027483,
                    0.39229
                ],
                "translation": [
                    -0.015,
                    0.015,
                    0.0
                ]
            }
        },
        {
            "id": 57282113,
            "internals": {
                "principal_point_px": [
                    3001.23,
                    2011.2434
                ],
                "focal_length_px": 5312.353,
                "radial_distortion": [
                    -0.01444223,
                    0.012321123,
                    -2.13311e-05
                ],
                "tangential_distortion": [
                    0.001239402,
                    0.000432234
                ],
                "type": "perspective"
            }
        }
    ]
}
