=== Pix4D/opf-spec/schema/scene_reference_frame.schema.json
{
    "$id": "scene_reference_frame.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Scene reference frame",
    "version": "1.0",
    "description": "An object that specifies a base Cartesian CRS and the transformation parameters to a translated canonical form suitable for processing and visualization.",
    "type": "object",
    "allOf": [
        {
            "$ref": "property.schema.json"
        }
    ],
    "properties": {
        "format": {
            "type": "string",
            "description": "For scene reference frame it must be `\"application/opf-scene-reference-frame+json\"`",
            "const": "application/opf-scene-reference-frame+json"
        },
        "version": {
            "$ref": "version.schema.json"
        },
        "crs": {
            "$ref": "crs.schema.json"
        },
        "base_to_canonical": {
            "$ref": "#/$defs/base_to_canonical"
        },
        "extensions": {}
    },
    "required": [
        "format",
        "version",
        "crs",
        "base_to_canonical"
    ],
    "$defs": {
        "base_to_canonical": {
            "type": "object",
            "title": "Base to translated canonical CRS transform",
            "allOf": [
                {
                    "$ref": "property.schema.json"
                }
            ],
            "properties": {
                "shift": {
                    "allOf": [
                        {
                            "$ref": "vector3d.schema.json"
                        }
                    ],
                    "description": "Translation from the canonical CRS to a recentered reference frame suitable for processing and visualization."
                },
                "scale": {
                    "allOf": [
                        {
                            "$ref": "vector3d.schema.json"
                        }
                    ],
                    "description": "Per axis scaling factors to make the base CRS isometric."
                },
                "swap_xy": {
                    "type": "boolean",
                    "description": "true if and only if the base CRS is left-handed."
                },
                "extensions": {}
            },
            "required": [
                "shift",
                "scale",
                "swap_xy"
            ]
        }
    }
}

=== Pix4D/opf-spec/examples/arbitrary-scene-reference-frame.json
{
    "format": "application/opf-scene-reference-frame+json",
    "version": "1.0",
    "crs": {
        "definition": "ENGINEERINGCRS[\"Construction site\",\n  ENGINEERINGDATUM[\"Southwest corner\"],\n  CS[Cartesian,3],\n    AXIS[\"northing (X)\",north,ORDER[1]],\n    AXIS[\"easting (Y)\",east,ORDER[2]],\n    AXIS[\"up (Z)\",up,ORDER[3]],\n    LENGTHUNIT[\"metre\",1.0]]"
    },
    "base_to_canonical": {
        "scale": [
            1.0,
            1.0,
            1.0
        ],
        "shift": [
            0,
            0,
            0
        ],
        "swap_xy": false
    }
}

=== Pix4D/opf-spec/examples/scene-reference-frame-extension.json
{
    "format": "application/opf-scene-reference-frame+json",
    "version": "1.0",
    "crs": {
        "definition": "PROJCRS[\"WGS 84 / UTM zone 16N\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"UTM zone 16N\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",-87,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",0.9996,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",500000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"(E)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"(N)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    ID[\"EPSG\",32616]]",
        "extensions": {
            "PIX4D_spatial_ref_sys": {
                "version": "1.0",
                "description": "this is a silly nonsensical example of extension",
                "grid_uri": "http://www.pix4d.com/grids/grid.zip"
            }
        }
    },
    "base_to_canonical": {
        "scale": [
            1.0,
            1.0,
            1.0
        ],
        "shift": [
            746308.1230880459,
            3714810.972981808,
            268.74755556838863
        ],
        "swap_xy": false
    }
}
